//
//  GothamHTFBook.swift
//  RealTimeTodo
//
//  Automatically generated by CSSToSwift on 27/10/2016.
//  Copyright © 2016 CSSToSwift. All rights reserved.
//

import UIKit

class GothamHTFBook : NSObject {

	let fontName: String = "GothamHTF-Book"
	let fontFamily: String = "Gotham HTF Book"
	let fontSubfamily: String = "Regular"

	enum GothamHTFBookEnum : String {
		case Space = "\u{32}";
		case Exclam = "\u{33}";
		case Quotedbl = "\u{34}";
		case Numbersign = "\u{35}";
		case Dollar = "\u{36}";
		case Percent = "\u{37}";
		case Ampersand = "\u{38}";
		case Quoteright = "\u{8217}";
		case Parenleft = "\u{40}";
		case Parenright = "\u{41}";
		case Asterisk = "\u{42}";
		case Plus = "\u{43}";
		case Comma = "\u{44}";
		case Hyphen = "\u{45}";
		case Period = "\u{46}";
		case Slash = "\u{47}";
		case Zero = "\u{48}";
		case One = "\u{49}";
		case Two = "\u{50}";
		case Three = "\u{51}";
		case Four = "\u{52}";
		case Five = "\u{53}";
		case Six = "\u{54}";
		case Seven = "\u{55}";
		case Eight = "\u{56}";
		case Nine = "\u{57}";
		case Colon = "\u{58}";
		case Semicolon = "\u{59}";
		case Less = "\u{60}";
		case Equal = "\u{61}";
		case Greater = "\u{62}";
		case Question = "\u{63}";
		case At = "\u{64}";
		case A = "\u{97}";
		case B = "\u{98}";
		case C = "\u{99}";
		case D = "\u{100}";
		case E = "\u{101}";
		case F = "\u{102}";
		case G = "\u{103}";
		case H = "\u{104}";
		case I = "\u{105}";
		case J = "\u{106}";
		case K = "\u{107}";
		case L = "\u{108}";
		case M = "\u{109}";
		case N = "\u{110}";
		case O = "\u{111}";
		case P = "\u{112}";
		case Q = "\u{113}";
		case R = "\u{114}";
		case S = "\u{115}";
		case T = "\u{116}";
		case U = "\u{117}";
		case V = "\u{118}";
		case W = "\u{119}";
		case X = "\u{120}";
		case Y = "\u{121}";
		case Z = "\u{122}";
		case Bracketleft = "\u{91}";
		case Backslash = "\u{92}";
		case Bracketright = "\u{93}";
		case Asciicircum = "\u{94}";
		case Underscore = "\u{95}";
		case Quoteleft = "\u{8216}";
		case Braceleft = "\u{123}";
		case Bar = "\u{124}";
		case Braceright = "\u{125}";
		case Asciitilde = "\u{126}";
		case Exclamdown = "\u{161}";
		case Cent = "\u{162}";
		case Sterling = "\u{163}";
		case Fraction = "\u{8260}";
		case Yen = "\u{165}";
		case Florin = "\u{402}";
		case Section = "\u{167}";
		case Currency = "\u{164}";
		case Quotesingle = "\u{39}";
		case Quotedblleft = "\u{8220}";
		case Guillemotleft = "\u{171}";
		case Guilsinglleft = "\u{8249}";
		case Guilsinglright = "\u{8250}";
		case Fi = "\u{64257}";
		case Fl = "\u{64258}";
		case Endash = "\u{8211}";
		case Dagger = "\u{8224}";
		case Daggerdbl = "\u{8225}";
		case Periodcentered = "\u{183}";
		case Paragraph = "\u{182}";
		case Bullet = "\u{8226}";
		case Quotesinglbase = "\u{8218}";
		case Quotedblbase = "\u{8222}";
		case Quotedblright = "\u{8221}";
		case Guillemotright = "\u{187}";
		case Ellipsis = "\u{8230}";
		case Perthousand = "\u{8240}";
		case Questiondown = "\u{191}";
		case Grave = "\u{96}";
		case Acute = "\u{180}";
		case Circumflex = "\u{710}";
		case Tilde = "\u{732}";
		case Macron = "\u{175}";
		case Breve = "\u{728}";
		case Dotaccent = "\u{729}";
		case Dieresis = "\u{168}";
		case Ring = "\u{730}";
		case Cedilla = "\u{184}";
		case Hungarumlaut = "\u{733}";
		case Ogonek = "\u{731}";
		case Caron = "\u{711}";
		case Emdash = "\u{8212}";
		case AE = "\u{198}";
		case Ordfeminine = "\u{170}";
		case Lslash = "\u{322}";
		case Oslash = "\u{248}";
		case OE = "\u{338}";
		case Ordmasculine = "\u{186}";
		case Ae = "\u{230}";
		case Dotlessi = "\u{305}";
		case Oe = "\u{339}";
		case Germandbls = "\u{223}";
		case Eth = "\u{240}";
		case Scaron = "\u{353}";
		case Yacute = "\u{253}";
		case Thorn = "\u{254}";
		case Zcaron = "\u{382}";
		case Adieresis = "\u{228}";
		case Aring = "\u{229}";
		case Ccedilla = "\u{231}";
		case Eacute = "\u{233}";
		case Ntilde = "\u{241}";
		case Odieresis = "\u{246}";
		case Udieresis = "\u{252}";
		case Aacute = "\u{193}";
		case Agrave = "\u{192}";
		case Acircumflex = "\u{194}";
		case Atilde = "\u{195}";
		case Egrave = "\u{200}";
		case Ecircumflex = "\u{202}";
		case Edieresis = "\u{203}";
		case Iacute = "\u{205}";
		case Igrave = "\u{204}";
		case Icircumflex = "\u{206}";
		case Idieresis = "\u{207}";
		case Oacute = "\u{211}";
		case Ograve = "\u{210}";
		case Ocircumflex = "\u{212}";
		case Otilde = "\u{213}";
		case Uacute = "\u{218}";
		case Ugrave = "\u{217}";
		case Ucircumflex = "\u{219}";
		case Degree = "\u{176}";
		case Registered = "\u{174}";
		case Copyright = "\u{169}";
		case Trademark = "\u{8482}";
		case Plusminus = "\u{177}";
		case Mu = "\u{181}";
		case Pi = "\u{960}";
		case Omega = "\u{937}";
		case Radical = "\u{8730}";
		case Approxequal = "\u{8776}";
		case Nbspace = "\u{160}";
		case Ydieresis = "\u{376}";
		case Apple = "\u{63743}";
	}

	func fontFile(size:CGFloat) -> UIFont? {
		return UIFont.init(name: fontName, size: size);
	}

}