//
//  UntitledFont15.swift
//  RealTimeTodo
//
//  Automatically generated by CSSToSwift on 27/10/2016.
//  Copyright © 2016 CSSToSwift. All rights reserved.
//

import UIKit

class UntitledFont15 : NSObject {

	let fontName: String = "untitled-font-15"
	let fontFamily: String = "untitled-font-15"
	let fontSubfamily: String = "font-15"

	enum UntitledFont15Enum : String {
		case IcCheckBlack24px = "\u{97}";
		case IcChevronLeftBlack24px = "\u{98}";
		case IcChevronRightBlack24px = "\u{99}";
		case IcCloseBlack24px = "\u{100}";
		case IcCommentBlack24px = "\u{101}";
		case IcDomainBlack24px = "\u{102}";
		case IcEventAvailableBlack24px1 = "\u{103}";
		case IcEventBlack24px = "\u{104}";
		case IcExpandLessBlack24px = "\u{105}";
		case IcExpandMoreBlack24px = "\u{106}";
		case IcFavoriteBlack24px = "\u{107}";
		case IcGradeBlack24px = "\u{108}";
		case IcHomeBlack24px = "\u{109}";
		case IcLanguageBlack24px1 = "\u{110}";
		case IcLinkBlack24px1 = "\u{111}";
		case IcLocalDiningBlack24px = "\u{112}";
		case IcLocationCityBlack24px = "\u{113}";
		case IcLocationOnBlack24px = "\u{114}";
		case IcMenuBlack24px = "\u{115}";
		case IcMoreVertBlack24px = "\u{116}";
		case IcNextWeekBlack24px = "\u{117}";
		case IcPersonAddBlack24px1 = "\u{118}";
		case IcSchoolBlack24px = "\u{119}";
		case IcSearchBlack24px = "\u{120}";
		case IcShoppingBasketBlack24px = "\u{121}";
		case IcStarsBlack24px = "\u{122}";
		case IcThumbDownBlack24px = "\u{65}";
		case IcThumbUpBlack24px = "\u{66}";
		case IcTuneBlack24px = "\u{67}";
		case IcWidgetsBlack24px = "\u{68}";
		case Soccer2 = "\u{69}";
		case Stethoscope1 = "\u{70}";
		case IcAccessTimeBlack24px = "\u{71}";
		case IcAccountBalanceBlack24px = "\u{72}";
		case IcArrowBackBlack24px = "\u{73}";
		case IcArrowDownwardBlack24px = "\u{74}";
		case IcArrowForwardBlack24px = "\u{75}";
		case IcArrowUpwardBlack24px = "\u{76}";
		case IcBookmarkBlack24px = "\u{77}";
		case IcBusinessBlack24px = "\u{78}";
		case IcCallBlack24px = "\u{79}";
		case TuneVertical = "\u{80}";
	}

	func fontFile(size:CGFloat) -> UIFont? {
		return UIFont.init(name: fontName, size: size);
	}

}