//
//  .swift
//  RealTimeTodo
//
//  Automatically generated by CSSToSwift on 29/10/2016.
//  Copyright © 2016 CSSToSwift. All rights reserved.
//

import UIKit

class  : NSObject {

	let fontName: String = ""
	let fontFamily: String = ""
	let fontSubfamily: String = ""

	enum  : String {
	}

	func fontFile(size:CGFloat) -> UIFont? {
		return UIFont.init(name: fontName, size: size);
	}

}